azurecloudify/server.py, blueprints/azure-windows-blueprint.yaml, blueprints/inputs/azure.yaml, blueprints/scripts/powershell/echo.ps1, blueprints/scripts/winrm/enable_winrm_http.ps1, plugin.yaml
Windows node_type updates
Adding debugging
D'oh again
D'oh
Bad URL
Fixing Windows hosts
=> Adding Windows host support + example

cloudify_azure/resources/compute/virtualmachine.py, cloudify_azure/resources/storage/file.py, cloudify_azure/resources/storage/storageaccount.py, system_tests/manager/resources/local-blueprint.yaml
Removed unnecessary debug output with sensitive information.
=> Logging updates

cloudify_azure/resources/compute/virtualmachine.py, examples/grid-compute/grid-compute.yaml, examples/grid-compute/scripts/example.py
- New grid-compute example showing high scalability and nested scaling policies and groups
- Updated VM resource name generator
=> Several updates, new example

cloudify_azure/resources/deployment.py, cloudify_azure/tests/resources/test_deployment.py, dev-requirements.txt, examples/resource_manager/deployment-file.yaml, examples/resource_manager/deployment-yaml.yaml, examples/resource_manager/deployment.yaml, examples/resource_manager/template.json, plugin.yaml, setup.py
=> support for ARM templates

cloudify_azure/resources/network/ipconfiguration.py
=> Static private ip address assignment in ipconfig

cloudify_azure/resources/deployment.py, cloudify_azure/tests/resources/test_deployment.py, plugin.yaml
- Add support for `use_external_resource`
- Set Deployment outputs in `runtime_properties['outputs']`
=> Deployment enhancements

CHANGELOG.txt, cloudify_azure/resources/deployment.py, cloudify_azure/tests/resources/test_deployment.py, cloudify_azure/utils.py, plugin.yaml
Reverts cloudify-incubator/cloudify-azure-plugin#121
=> Revert "adding resource group"

cloudify_azure/utils.py
=> CYBL-995-Fix-Flake8

CHANGELOG.txt, cloudify_azure/resources/compute/managed_cluster.py, cloudify_azure/tests/resources/test_managed_cluster.py, examples/aks_service/managed-cluster-blueprint.yaml, examples/aks_service/scripts/store_kube_token.py, plugin.yaml, setup.py
=> CY-2267-AKS-support

examples/aks_service/managed-cluster-blueprint.yaml, examples/aks_service/scripts/store_kube_token.py
=> CY-2267-Example-Update

CHANGELOG.txt, cloudify_azure/resources/compute/virtualmachine.py, plugin.yaml, setup.py
Fixed the issue when creating the extension it was related to format of input
=> CY-2818-Fix-Virtual-Machine-ExtensionForWindows

cloudify_azure/resources/compute/virtualmachine.py, cloudify_azure/tests/resources/test_compute.py, cloudify_azure/utils.py
=> fix network profile

plugin.yaml
Adding `__NODOCS__` to fix validate documentation step
=> __NODOCS__

README.md
NODOCS
Fixed link to DOCS to be latest
Pls review
=> Update README.md NODOCS

.circleci/config.yml
=> pin pip py3

.circleci/update_test_manager.py, CHANGELOG.txt, azure_sdk/resources/deployment.py, azure_sdk/resources/resource_group.py, cloudify_azure/resources/deployment.py, cloudify_azure/tests/resources/test_deployment.py, plugin.yaml
This PR implements pull for Azure arm deployments.
The sensitivity of drifts is the deletion of resources.
The idea is to check which resources are created in the template, search them in the resource group, and if resources are not found use the what-if result. (there  are resources like subnet that does not appear under the resource group)
=> Rd 1795 add pull for azurearm

CHANGELOG.txt, cloudify_azure/constants.py, cloudify_azure/resources/compute/virtualmachine.py, cloudify_azure/resources/compute/virtualmachine/virtualmachine.py, cloudify_azure/resources/compute/virtualmachine/virtualmachine_utils.py, cloudify_azure/resources/network/loadbalancer.py, cloudify_azure/resources/network/networkinterfacecard.py, cloudify_azure/tests/resources/test_compute.py, cloudify_azure/tests/resources/test_virtualmachine_utils.py, plugin.yaml, setup.py
Added code in order to find if there is any difference between the VM update payload and the current VM config.
if there is a change in the update payload we will execute the update.
In the current VM configuration, it is possible to have fields that don't appear in the update payload, it will not be considered as diff.
=> Rd 2266 update azure vm

.circleci/config.yml, tox.ini
added unites orb for unites and validations
=> unittest orb

CHANGELOG.txt, azure_sdk/resources/compute/virtual_machine_extension.py, cloudify_azure/resources/compute/virtualmachine/virtualmachine.py, plugin.yaml, v2_plugin.yaml
seems that we are calling a wrong API in virtual machine extension.
=> RD-5034-Fix-VirtualMachine-Extension

CHANGELOG.txt, cloudify_azure/resources/compute/virtualmachine/virtualmachine.py, cloudify_azure/resources/compute/virtualmachineextension.py, plugin.yaml, scripts/ps_enable_winrm_http.ps1, v2_plugin.yaml
fix the input for virtual_machine_extenstion type  and adjust enable_winrm power_shell script so it would switch network type to private
=> RD-5034-Fix-VirtualMachineExtension-Inputs

CHANGELOG.txt, azure_sdk/resources/compute/virtual_machine.py, cloudify_azure/resources/compute/virtualmachine/virtualmachine.py, cloudify_azure/tests/resources/test_compute.py, plugin.yaml, plugin_1_4.yaml, v2_plugin.yaml
Added resize VM operation
Added restart VM operation
=> Support vm resize and restart

.circleci/config.yml, CHANGELOG.txt, cloudify_azure/tests/resources/test_network.py, cloudify_azure/utils.py
Skip Tags from convert case logic that we have in-place to map REST to SDK parameters names variation
=> Ignore-Tags-ConvertCase
